name: Build artifacts
on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Chmod
        run: chmod +x ./build.sh

      - name: Find tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        continue-on-error: true
        with:
          commit-ish: 'HEAD'

      - name: Build
        run: ./build.sh ozz-ms/ozz-srv
        env:
          CI_COMMIT_TAG: ${{steps.tagger.outputs.tag}}
