name: Release executables

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Chmod
        run: chmod +x ./build.sh

      - name: Find tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        continue-on-error: true
        with:
          commit-ish: 'HEAD'

      - name: Build
        run: ./build.sh ozz-ms/ozz-srv
        env:
          CI_COMMIT_TAG: ${{steps.tagger.outputs.tag}}

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./artifacts/**
          automatic_release_tag: "latest"
